import { cloudinaryUrl } from './cloudinary';

export const IMAGE_URLS = {
  header: {
    background: cloudinaryUrl('DMKITTI/bg_u2kwuw.webp'),
    baratfuleSign: cloudinaryUrl('DMKITTI/10_bmdspi.webp'),
    cozyTeaTime: cloudinaryUrl('DMKITTI/3_ahv5cx.webp'),
    sos: cloudinaryUrl('DMKITTI/22_izyrxa.webp'),
    coffeeGathering: cloudinaryUrl('DMKITTI/15_lh0ydh.webp'),
  },
  about: {
    baratfuleSign: cloudinaryUrl('DMKITTI/19_ebodcq.webp'),
    kittiPortrait: cloudinaryUrl('DMKITTI/9_se3bgd.webp'),
    workshopImage: cloudinaryUrl('DMKITTI/7_enuetb.webp'),
    pite: cloudinaryUrl('DMKITTI/22_izyrxa.webp'),
  },
  home: {
    bg: cloudinaryUrl('DMKITTI/bg.png'),
    heritageWorkshop: cloudinaryUrl('DMKITTI/18_dw3xjr.webp'),
    serviceCandy_2: cloudinaryUrl('DMKITTI/6_nrpg1l.webp'),
    serviceCandy: cloudinaryUrl('DMKITTI/10_bmdspi.webp'),
    heritageGathering: cloudinaryUrl('DMKITTI/13_qauto0.webp'),
    turosLepeny: cloudinaryUrl('DMKITTI/22_izyrxa.webp'),
    bf: cloudinaryUrl('DMKITTI/21_e2xq7k.webp'),
    sos: cloudinaryUrl('DMKITTI/20_fjfjvn.webp'),
  },
  gallery: [
    '/gallery/1.jpg',
    '/gallery/2.jpg',
    '/gallery/3.jpg',
    '/gallery/4.jpg',
    '/gallery/5.jpg',
    '/gallery/6.jpg',
    '/gallery/7.jpg',
    '/gallery/8.jpg',
    '/gallery/9.jpg',
    '/gallery/10.jpg',
    '/gallery/11.jpg',
    '/gallery/12.jpg',
    '/gallery/13.jpg',
    '/gallery/14.jpg',
    '/gallery/15.jpg',
    '/gallery/16.jpg',
    '/gallery/17.jpg',
    '/gallery/18.jpg',
    '/gallery/19.jpg',
    '/gallery/20.jpg',
    '/gallery/21.jpg',
    '/gallery/22.jpg',
    '/gallery/23.jpg',
    '/gallery/24.jpg',
    '/gallery/25.jpg',
    '/gallery/26.jpg',
  ],
};
