import type { Metadata } from 'next';
import '@/app/_style/globals.css';
import Footer from './_components/Footer';
import Header from './_components/Header';
import Navigation from './_components/Navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hu">
      <body className="antialiased flex min-h-screen w-full flex-col bg-background">
        <Navigation />
        <Header />
        <main className="flex flex-1 flex-col">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
